steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/inventory-app:$COMMIT_SHA', '.']

  # Paso 2: Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/inventory-app:$COMMIT_SHA']

  # Paso 3: Implementar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-to-Cloud-Run
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'inventory-app'
      - '--image=us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/inventory-app:$COMMIT_SHA'
      - '--region=us-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY